<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNpVSt6x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNpVSt6x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNpVSt6x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNpVSt6x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNpVSt6x\App_KernelDevDebugContainer([
    'container.build_hash' => 'NpVSt6x',
    'container.build_id' => 'dc027552',
    'container.build_time' => 1741855841,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNpVSt6x');
