<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZxe6QK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZxe6QK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFZxe6QK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFZxe6QK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFZxe6QK\App_KernelDevDebugContainer([
    'container.build_hash' => 'FZxe6QK',
    'container.build_id' => '734c9bed',
    'container.build_time' => 1741837589,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZxe6QK');
